input_select:
  chore_laundry:
    name: Pesutoimkond
    icon: mdi:washing-machine
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_trash:
    name: Prügitoimkond
    icon: mdi:trash-can
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_bathroom_1:
    name: Tualetitoimkond 1. korrus
    icon: mdi:toilet
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_bathroom_basement:
    name: Tualetitoimkond sokkel
    icon: mdi:shower
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_plants:
    name: Floratoimkond
    icon: mdi:flower
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_cat:
    name: Kassitoimkond
    icon: mdi:cat
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_dust_1:
    name: Tolmutoimkond 1. korrus
    icon: mdi:vacuum
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_dust_basement:
    name: Tolmutoimkond sokkel
    icon: mdi:broom
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  chore_kitchen:
    name: Köögitoimkond
    icon: mdi:silverware-fork-knife
    options:
      - person.eero_otsus
      - person.katlyn_otsus
      - person.lola_laur

  ada_helper_eero:
    name: Ada abistab Eerot
    icon: mdi:account-plus
    options:
      - chore_laundry
      - chore_trash
      - chore_bathroom_1
      - chore_bathroom_basement
      - chore_plants
      - chore_cat
      - chore_dust_1
      - chore_dust_basement
      - chore_kitchen

  ada_helper_katlyn:
    name: Ada abistab Kätlyni
    icon: mdi:account-plus
    options:
      - chore_laundry
      - chore_trash
      - chore_bathroom_1
      - chore_bathroom_basement
      - chore_plants
      - chore_cat
      - chore_dust_1
      - chore_dust_basement
      - chore_kitchen

  ada_helper_lola:
    name: Ada abistab Lolat
    icon: mdi:account-plus
    options:
      - chore_laundry
      - chore_trash
      - chore_bathroom_1
      - chore_bathroom_basement
      - chore_plants
      - chore_cat
      - chore_dust_1
      - chore_dust_basement
      - chore_kitchen

input_datetime:
  chore_last_rotation:
    name: Last Chore Rotation
    has_date: true
    has_time: false
